### Create a new item
POST http://localhost:3000/items
Content-Type: application/json

{
  "id": 1,
  "name": "Test Item",
  "description": "This is a test item"
}

### Read all items
GET http://localhost:3000/items

### Update an item
PUT http://localhost:3000/items/1
Content-Type: application/json

{
  "name": "Updated Test Item",
  "description": "This is an updated test item"
}

### Delete an item
DELETE http://localhost:3000/items/1

### Create another item
POST http://localhost:3000/items
Content-Type: application/json

{
  "id": 2,
  "name": "Second Item",
  "description": "This is another test item"
}

### Read all items again
GET http://localhost:3000/items